/**
 * `candle completion zsh|bash|fish` (BE-238, spec 0.11.1 D7).
 *
 * Static scripts, generated from `help.ts` and nothing else. Because `HELP` is pinned to dispatch
 * by the drift test (T1/T2), a completion script cannot offer a command that does not route; and
 * because the flags are read from the same rows the help prints, the script offers exactly what
 * the help documents.
 *
 * Dispatched before `migrateProfiles` / `resolveProfileName` (`index.ts`), the same skip `help`
 * gets: completions are how the operator stranded by BE-235's item 4 discovers `CANDLE_CONFIG_DIR`,
 * so they have to work with no identity. This command reads no config and makes no request.
 *
 * No dynamic completion in this release: profile names, key labels and factor ids are not
 * completed, because completing a label would mean opening the vault at tab time and completing a
 * profile name would mean reading config at tab time from a shell hook. Neither belongs in a first
 * cut.
 *
 * `--json` is a usage error here, not a silent text payload: the script IS the payload and it has
 * no JSON form, which is the rule `vault restore` already applies to itself. That is not the
 * command becoming TTY-only -- `candle completion zsh > file` works from any pipe or agent.
 *
 * Every `${...}` in the emitted lines below is SHELL expansion inside a single-quoted TypeScript
 * string (`${words[2]}`, `${COMP_WORDS[1]}`): the generated script reads them at completion time,
 * and turning them into template literals -- which is what noTemplateCurlyInString suggests --
 * would interpolate them here and emit an empty word.
 */
// biome-ignore-all lint/suspicious/noTemplateCurlyInString: shell expansions in the generated script, not TS interpolation
import type { CommandContext } from "../deps"
import { COMPLETION_SHELLS, documentedFlags, documentedSubcommands, FACTOR_KINDS, GLOBAL_FLAGS, HELP } from "../help"
import { writeUsageFailure } from "../render"

const USAGE = `Usage: candle completion <${COMPLETION_SHELLS.join("|")}>`

/** The one two-word path with a fixed vocabulary worth completing: `vault factor`'s own words and
 * the four kinds `add` takes. Both come from `help.ts`, so a completion cannot offer a kind the
 * help never names. Nothing else is completed by value in this release (see the file comment). */
const VAULT_FACTOR_VALUES = ["list", "add", "remove", ...FACTOR_KINDS]

/** Every word a user may type as the command: the canonical routed words plus the friendlier
 * spellings the top level displays (`wallet` for `wallets`). */
function completableWords(): string[] {
  const words = new Set<string>()
  for (const [canonical, topic] of Object.entries(HELP)) {
    words.add(canonical)
    if (topic.display) words.add(topic.display)
  }
  return [...words].sort()
}

/** The global flags, as bare tokens. `--help, -h` is one row documenting two flags. */
function globalFlagTokens(): string[] {
  const tokens = new Set<string>()
  for (const row of GLOBAL_FLAGS) {
    for (const token of row.invocation.split(/[\s,]+/)) if (token.startsWith("-")) tokens.add(token)
  }
  return [...tokens].sort()
}

/** What a command word offers after itself: its subcommands, then its flags. */
function perWord(): { word: string; subcommands: string[]; flags: string[] }[] {
  const out: { word: string; subcommands: string[]; flags: string[] }[] = []
  for (const [canonical, topic] of Object.entries(HELP)) {
    const entry = { subcommands: documentedSubcommands(topic), flags: documentedFlags(topic) }
    out.push({ word: canonical, ...entry })
    if (topic.display) out.push({ word: topic.display, ...entry })
  }
  return out.sort((a, b) => a.word.localeCompare(b.word))
}

/** Single quotes cannot be escaped inside a single-quoted shell word, and a stray colon splits a
 * zsh completion description. Descriptions in a generated script are cosmetic, so they are
 * flattened rather than escaped: a script that fails to parse is worse than a terser description. */
function safe(text: string): string {
  return text
    .replace(/['`$\\]/g, "")
    .replace(/:/g, " -")
    .replace(/\s+/g, " ")
    .trim()
}

function zshScript(): string {
  const lines = [
    "#compdef candle",
    "# Generated by: candle completion zsh",
    "# Regenerate after every candle update.",
    "",
    "_candle() {",
    "  local -a _candle_words _candle_subs _candle_flags _candle_globals",
    `  _candle_words=(${completableWords().join(" ")})`,
    `  _candle_globals=(${globalFlagTokens().join(" ")})`,
    "  _candle_subs=()",
    "  _candle_flags=()",
    '  case "${words[2]}" in',
  ]
  for (const { word, subcommands, flags } of perWord()) {
    lines.push(`    ${word})`)
    if (subcommands.length > 0) lines.push(`      _candle_subs=(${subcommands.join(" ")})`)
    if (flags.length > 0) lines.push(`      _candle_flags=(${flags.join(" ")})`)
    lines.push("      ;;")
  }
  lines.push(
    "  esac",
    '  case "${words[2]} ${words[3]}" in',
    `    "vault factor") _candle_subs=(${VAULT_FACTOR_VALUES.join(" ")}) ;;`,
    "  esac",
    "  if (( CURRENT == 2 )); then",
    "    compadd -- $_candle_words",
    "  else",
    "    compadd -- $_candle_subs $_candle_flags $_candle_globals",
    "  fi",
    "}",
    "",
    "compdef _candle candle",
    "",
  )
  return lines.join("\n")
}

function bashScript(): string {
  const lines = [
    "# Generated by: candle completion bash",
    "# Regenerate after every candle update.",
    "",
    "_candle() {",
    "  local cur candle_words candle_subs candle_flags candle_globals",
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    `  candle_words="${completableWords().join(" ")}"`,
    `  candle_globals="${globalFlagTokens().join(" ")}"`,
    '  candle_subs=""',
    '  candle_flags=""',
    '  if [ "$COMP_CWORD" -eq 1 ]; then',
    '    COMPREPLY=( $(compgen -W "$candle_words" -- "$cur") )',
    "    return 0",
    "  fi",
    '  case "${COMP_WORDS[1]}" in',
  ]
  for (const { word, subcommands, flags } of perWord()) {
    lines.push(`    ${word})`)
    if (subcommands.length > 0) lines.push(`      candle_subs="${subcommands.join(" ")}"`)
    if (flags.length > 0) lines.push(`      candle_flags="${flags.join(" ")}"`)
    lines.push("      ;;")
  }
  lines.push(
    "  esac",
    '  if [ "$COMP_CWORD" -ge 3 ] && [ "${COMP_WORDS[1]}" = "vault" ] && [ "${COMP_WORDS[2]}" = "factor" ]; then',
    `    candle_subs="${VAULT_FACTOR_VALUES.join(" ")}"`,
    "  fi",
    '  COMPREPLY=( $(compgen -W "$candle_subs $candle_flags $candle_globals" -- "$cur") )',
    "}",
    "",
    "complete -F _candle candle",
    "",
  )
  return lines.join("\n")
}

function fishScript(): string {
  const lines = [
    "# Generated by: candle completion fish",
    "# Regenerate after every candle update.",
    "",
    "complete -c candle -f",
    "",
  ]
  for (const [canonical, topic] of Object.entries(HELP)) {
    for (const word of topic.display ? [canonical, topic.display] : [canonical]) {
      lines.push(`complete -c candle -n '__fish_use_subcommand' -a '${word}' -d '${safe(topic.summary)}'`)
    }
  }
  lines.push("")
  for (const row of GLOBAL_FLAGS) {
    for (const token of row.invocation.split(/[\s,]+/)) {
      if (token.startsWith("--")) lines.push(`complete -c candle -l '${token.slice(2)}' -d '${safe(row.description)}'`)
      else if (token.startsWith("-") && token.length === 2) {
        lines.push(`complete -c candle -s '${token.slice(1)}' -d '${safe(row.description)}'`)
      }
    }
  }
  for (const { word, subcommands, flags } of perWord()) {
    if (subcommands.length === 0 && flags.length === 0) continue
    lines.push("")
    for (const sub of subcommands) {
      lines.push(`complete -c candle -n '__fish_seen_subcommand_from ${word}' -a '${sub}'`)
    }
    for (const flag of flags) {
      if (flag.startsWith("--")) {
        lines.push(`complete -c candle -n '__fish_seen_subcommand_from ${word}' -l '${flag.slice(2)}'`)
      } else lines.push(`complete -c candle -n '__fish_seen_subcommand_from ${word}' -s '${flag.slice(1)}'`)
    }
  }
  lines.push("")
  for (const kind of VAULT_FACTOR_VALUES) {
    lines.push(`complete -c candle -n '__fish_seen_subcommand_from factor' -a '${kind}'`)
  }
  lines.push("")
  return lines.join("\n")
}

const SCRIPTS: Record<string, () => string> = { zsh: zshScript, bash: bashScript, fish: fishScript }

async function writeScript(shell: (typeof COMPLETION_SHELLS)[number], ctx: CommandContext): Promise<number> {
  if (ctx.json) {
    writeUsageFailure(
      ctx.deps,
      `candle completion ${shell} has no --json form: the completion script is the output. Redirect it instead: candle completion ${shell} > <path>`,
      true,
    )
    return 2
  }
  ctx.deps.stdout.write((SCRIPTS[shell] as () => string)())
  return 0
}

export async function completionZsh(_args: string[], ctx: CommandContext): Promise<number> {
  return writeScript("zsh", ctx)
}

export async function completionBash(_args: string[], ctx: CommandContext): Promise<number> {
  return writeScript("bash", ctx)
}

export async function completionFish(_args: string[], ctx: CommandContext): Promise<number> {
  return writeScript("fish", ctx)
}

/** `candle completion` with no shell, or one that is not among the three. Dispatch reaches this
 * bare form only when no subcommand matched, so an unknown shell and a missing one answer alike:
 * a usage error naming the three, exit 2. */
export async function completion(args: string[], ctx: CommandContext): Promise<number> {
  const typed = args.find((arg) => !arg.startsWith("-"))
  const named = typed === undefined ? "No shell named." : `Unknown shell: ${typed}.`
  writeUsageFailure(ctx.deps, `${named} ${USAGE}`, ctx.json)
  return 2
}
