/**
 * T49 (CC-09): the committed fixture vault opens in every shape this package ships in, and the
 * T53 vectors give the same answers in each.
 *
 * The shapes are three: `bun test` in the monorepo (this process), the exported
 * `candledottv/agentic` mirror's own `bun test` before it builds a release, and the compiled
 * single-file binary. The first and the third run here; the second runs the same file, unchanged,
 * because it is committed to this package and the mirror copies it. The third is driven on a
 * pseudo-terminal, because the binary's only way to a passphrase is its hidden prompt and a check
 * that never typed one was reading the public header and calling it parity.
 *
 * What this catches is the class of failure that only appears at release time: a bundler or a
 * runtime difference that changes a derived address. Nothing else in the suite would notice --
 * every other test derives and checks in one process, so the code agreeing with itself is enough.
 * Here the FIXTURE is the fixed point: bytes written once, by `scripts/build-vault-fixture.ts`, at
 * ED-3's real cost, and every shape has to reproduce the same address from them.
 */
import { describe, expect, setDefaultTimeout, test } from "bun:test"
import { spawnSync } from "node:child_process"
import { copyFileSync, existsSync, mkdtempSync, readFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"
import { addressFromSecret64 } from "./ed25519"
import { deriveSolanaKey, phraseFromEntropy, solanaVaultPath } from "./hd"
import { wipe } from "./hygiene"
import { closeVault, decryptKey, decryptRoot, unlockWithPassphrase } from "./store"
import { FIXTURE_ENTROPY, FIXTURE_PASSPHRASE, FIXTURE_PHRASE, generatedPassphraseFrom } from "./test-vault"
import { verifyVaultIntegrity } from "./verify"

/**
 * These tests run REAL Argon2id, which is the point of them: a vault suite that stubbed the KDF
 * would not be testing the format anyone actually opens. Even at ED-3's bounds floor (see
 * `useCheapKdf`) a single derivation is a few hundred milliseconds, several tests here do five or
 * six of them, and a CI runner sharing a box with every other workspace's suite is slower again.
 * Bun's default per-test budget is 5 s, which one of these exceeded on CI while passing locally --
 * so the budget is stated here rather than discovered once per runner.
 */
setDefaultTimeout(180_000)

const pkgDir = resolve(import.meta.dir, "..", "..")
const fixturePath = join(pkgDir, "test-fixtures", "vault", "vault.enc")

/** The fixture's one derived key, recorded here so a shape that differs is a named failure. */
const FIXTURE_ADDRESS = "5Pobwp6d9ihN9Nz38f87gVCEBFMgipFiSM2VtUhVit6w"
const FIXTURE_PATH = "m/44'/501'/0'/0'"

describe("T49: the committed fixture, under bun test in the monorepo", () => {
  test("it exists, carries ED-3's real cost, and is not regenerated by the test that reads it", () => {
    expect(existsSync(fixturePath)).toBe(true)
    const file = JSON.parse(readFileSync(fixturePath, "utf8")) as {
      version: number
      envelopes: Array<{ kdf: { m: number; t: number } }>
    }
    expect(file.version).toBe(2)
    // The one artifact that should look exactly like a real vault: a fixture at the tests' cheap
    // floor would not exercise what an operator's file actually costs to open.
    expect(file.envelopes[0]?.kdf).toMatchObject({ m: 65536, t: 3 })
  })

  test("it opens with the fixture passphrase, and its key re-derives from its own root", async () => {
    const raw = readFileSync(fixturePath, "utf8")
    const vault = await unlockWithPassphrase(fixturePath, raw, FIXTURE_PASSPHRASE)
    try {
      expect(vault.index.entries).toHaveLength(1)
      const entry = vault.index.entries[0]
      expect(entry?.address).toBe(FIXTURE_ADDRESS)
      expect(entry?.derivation?.path).toBe(FIXTURE_PATH)

      const secret = await decryptKey(vault, entry?.id as string)
      expect(addressFromSecret64(secret)).toBe(FIXTURE_ADDRESS)
      wipe(secret)

      // The root is the fixture's synthetic entropy, and it renders the phrase the tests name.
      const root = await decryptRoot(vault)
      expect([...root]).toEqual([...FIXTURE_ENTROPY])
      expect(phraseFromEntropy(root)).toBe(FIXTURE_PHRASE)
      wipe(root)
    } finally {
      closeVault(vault)
    }
  })

  test("all eight verifier steps pass on it", async () => {
    const raw = readFileSync(fixturePath, "utf8")
    const vault = await unlockWithPassphrase(fixturePath, raw, FIXTURE_PASSPHRASE)
    try {
      const report = await verifyVaultIntegrity(vault)
      expect(report.rederived).toHaveLength(1)
      expect(report.notRederived).toHaveLength(0)
    } finally {
      closeVault(vault)
    }
  })

  test("the T53 vectors give the recorded address in this shape", async () => {
    const derived = await deriveSolanaKey(Uint8Array.from(FIXTURE_ENTROPY), FIXTURE_PATH)
    expect(derived.address).toBe(FIXTURE_ADDRESS)
    wipe(derived.secret64)
  })
})

describe("T49: the same fixture, through the COMPILED binary, on a real terminal", () => {
  // `release-verify.compiled.test.ts` is the precedent for compiling inside a test. It costs a few
  // seconds and it is the only way to see a bundler or runtime difference before a release does.
  const binary = join(pkgDir, "dist-bin", "candle-vault-parity")

  /**
   * A copy of the fixture in a private config dir: the binary's `new-key` writes to the vault it
   * opens and every unlock writes the sidecar beside it, and neither may touch the committed
   * bytes. The copy IS the committed bytes, which is what makes the open below a parity check.
   */
  const workDir = mkdtempSync(join(tmpdir(), "candle-vault-parity-"))
  const copy = join(workDir, "vault.enc")
  copyFileSync(fixturePath, copy)
  const teeIndexSeenBefore = readFileSync(fixturePath)

  /**
   * Runs the compiled binary on a pseudo-terminal Bun allocates, so stdin and stdout are both
   * TTYs and the binary's own hidden prompt is what collects the passphrase. There is no other
   * way in, by design: no flag, no environment variable and no pipe supplies a vault passphrase
   * (spec: hidden prompt only), so a compiled check that skipped the prompt was not opening
   * anything. Each scripted answer is typed once its prompt has appeared, in order.
   *
   * What comes back is the terminal's transcript, stdout and stderr merged as a terminal shows
   * them; the stdout-alone `--json` contract is asserted by the command tests through fake deps.
   */
  async function onTerminal(
    args: string[],
    answers: Array<{ at: string; type: string }>,
    env: Record<string, string> = {},
  ): Promise<{ code: number; transcript: string }> {
    const decoder = new TextDecoder()
    const chunks: string[] = []
    const proc = Bun.spawn([binary, ...args], {
      cwd: workDir,
      env: {
        ...process.env,
        CANDLE_CONFIG_DIR: workDir,
        // The file-backed secret store asks for its own passphrase on a terminal, which is not the
        // prompt under test; this satisfies it without a prompt. No API key is stored, so no
        // command below reaches the network.
        CANDLE_KEYRING_PASSPHRASE: "vault-parity-test",
        ...env,
      },
      terminal: {
        cols: 200,
        rows: 50,
        data: (_terminal, data) => {
          chunks.push(decoder.decode(data))
        },
      },
    })
    const transcript = () => chunks.join("").replace(/\r\n/g, "\n")
    const queue = [...answers]
    let cursor = 0
    const started = Date.now()
    while (queue.length > 0) {
      if (Date.now() - started > 120_000) {
        proc.kill()
        throw new Error(`timed out waiting for the prompt "${queue[0]?.at}"; transcript so far:\n${transcript()}`)
      }
      const next = queue[0] as { at: string; type: string }
      const seen = transcript().indexOf(next.at, cursor)
      if (seen >= 0) {
        cursor = seen + next.at.length
        proc.terminal?.write(`${next.type}\r`)
        queue.shift()
      }
      await Bun.sleep(25)
    }
    const code = await proc.exited
    return { code, transcript: transcript() }
  }

  /** The one `--json` value in a transcript: the line that carries it, from its first brace. */
  function jsonIn(transcript: string): Record<string, unknown> {
    const carriers = transcript.split("\n").filter((line) => line.includes('{"ok":'))
    expect(carriers).toHaveLength(1)
    const line = carriers[0] as string
    return JSON.parse(line.slice(line.indexOf('{"ok":'))) as Record<string, unknown>
  }

  test("it compiles", () => {
    const built = spawnSync("bun", ["build", "--compile", "src/index.ts", "--outfile", binary], {
      cwd: pkgDir,
      encoding: "utf8",
    })
    expect(`compile exited ${built.status}: ${built.stderr}`).toBe(`compile exited 0: ${built.stderr}`)
    expect(existsSync(binary)).toBe(true)
  })

  test("the compiled binary UNLOCKS the fixture through its own hidden prompt and reports the same key", async () => {
    const { code, transcript } = await onTerminal(
      ["vault", "status", "--unlock", "--json", "--keystore", copy],
      [{ at: "Vault passphrase (input hidden): ", type: FIXTURE_PASSPHRASE }],
    )
    expect(`status exited ${code}:\n${transcript}`).toStartWith("status exited 0:")
    const body = jsonIn(transcript) as {
      ok: boolean
      version: number
      envelopes: Array<{ factor: string; strength: string }>
      unlocked: {
        entries: Array<{ address: string; derivation: string; role: string }>
        nextIndex: { solanaVault: number }
      }
    }
    expect(body.ok).toBe(true)
    expect(body.version).toBe(2)
    expect(body.envelopes[0]).toMatchObject({ factor: "passphrase", strength: "generated-103" })
    // The index was DECRYPTED in this shape: Argon2id, the DEK unwrap, HKDF and AES-GCM all ran
    // inside the binary, and the entry it reports is the one the monorepo shape reads above.
    expect(body.unlocked.entries).toHaveLength(1)
    expect(body.unlocked.entries[0]).toMatchObject({
      address: FIXTURE_ADDRESS,
      derivation: FIXTURE_PATH,
      role: "vault",
    })
    expect(body.unlocked.nextIndex.solanaVault).toBe(1)
    // The hidden prompt swallowed the passphrase: it is nowhere in what the terminal showed.
    expect(transcript).not.toContain(FIXTURE_PASSPHRASE)
  })

  test("the compiled binary DERIVES from the fixture's root, and the address is this shape's (T53 in the compiled shape)", async () => {
    // Index 1 is the next this fixture allocates. Derived here, in this process, from the fixture
    // entropy; the binary must reach the same address from the root blob it decrypts, through
    // the BIP-39 seed and SLIP-0010 as bundled and compiled. This is the assertion that catches a
    // bundler inlining a different wordlist or a different hash: a compiled binary that agreed
    // with itself would still pass a status read, and would not pass this.
    const expected = await deriveSolanaKey(Uint8Array.from(FIXTURE_ENTROPY), solanaVaultPath(1))
    wipe(expected.secret64)

    const { code, transcript } = await onTerminal(
      ["vault", "new-key", "--chain", "solana", "--json", "--keystore", copy],
      [{ at: "Vault passphrase (input hidden): ", type: FIXTURE_PASSPHRASE }],
    )
    expect(`new-key exited ${code}:\n${transcript}`).toStartWith("new-key exited 0:")
    const body = jsonIn(transcript) as { ok: boolean; address: string; path: string; index: number }
    expect(body.ok).toBe(true)
    expect(body.index).toBe(1)
    expect(body.path).toBe(solanaVaultPath(1))
    expect(body.address).toBe(expected.address)
    expect(transcript).not.toContain(FIXTURE_PASSPHRASE)

    // And what the binary WROTE opens in this shape with that key re-derived from the root: the
    // two shapes agree on the file, not only on the printed address.
    const vault = await unlockWithPassphrase(copy, readFileSync(copy, "utf8"), FIXTURE_PASSPHRASE)
    try {
      expect(vault.index.entries.map((entry) => entry.address)).toEqual([FIXTURE_ADDRESS, expected.address])
      const report = await verifyVaultIntegrity(vault)
      expect(report.rederived).toHaveLength(2)
    } finally {
      closeVault(vault)
    }
    // The committed fixture is untouched.
    expect(readFileSync(fixturePath).equals(teeIndexSeenBefore)).toBe(true)
  })

  test("the compiled binary RESTORES from the fixture phrase and re-derives the fixture address (BIP-39 as compiled)", async () => {
    // The one path that starts from WORDS rather than from a root blob: the phrase typed at the
    // binary's hidden prompt goes through the bundled wordlist and checksum, the seed, SLIP-0010
    // and the address encoding, all inside the binary, and index 0 must come out as the address
    // the fixture recorded. The generated passphrase it shows is read off the terminal, as an
    // operator would, and typed back; no API key is stored, so no exposure read is attempted.
    const restored = join(workDir, "restored.enc")
    const typedBack: { at: string; type: string } = { at: "Type it back in full to confirm (input hidden): ", type: "" }
    const decoder = new TextDecoder()
    const chunks: string[] = []
    const proc = Bun.spawn(
      [binary, "vault", "restore", "--phrase", "--count", "1", "--tee-count", "0", "--keystore", restored],
      {
        cwd: workDir,
        env: { ...process.env, CANDLE_CONFIG_DIR: workDir, CANDLE_KEYRING_PASSPHRASE: "vault-parity-test" },
        terminal: {
          cols: 200,
          rows: 50,
          data: (_terminal, data) => {
            chunks.push(decoder.decode(data))
          },
        },
      },
    )
    const transcript = () => chunks.join("").replace(/\r\n/g, "\n")
    const waitFor = async (text: string, from: number): Promise<number> => {
      const started = Date.now()
      for (;;) {
        const seen = transcript().indexOf(text, from)
        if (seen >= 0) return seen + text.length
        if (Date.now() - started > 120_000) {
          proc.kill()
          throw new Error(`timed out waiting for "${text}"; transcript so far:\n${transcript()}`)
        }
        await Bun.sleep(25)
      }
    }
    let cursor = await waitFor("Recovery phrase (24 words, input hidden): ", 0)
    proc.terminal?.write(`${FIXTURE_PHRASE}\r`)
    cursor = await waitFor(typedBack.at, cursor)
    // The passphrase the binary generated and showed, scraped from the terminal exactly as the
    // command tests scrape it from a captured stdout.
    typedBack.type = generatedPassphraseFrom(transcript())
    proc.terminal?.write(`${typedBack.type}\r`)
    const code = await proc.exited
    const text = transcript()
    expect(`restore exited ${code}:\n${text}`).toStartWith("restore exited 3:")
    expect(text).toContain("verified in full (all eight steps)")
    // Either no key at all, or a stored key the API refuses: both paths leave exposure unrecorded,
    // and that is the claim this check needs. Naming only the empty-store sentence failed on a
    // machine whose keyring held an invalid key under the test passphrase.
    expect(text).toContain("No exposure was recorded")
    expect(text).toContain(FIXTURE_ADDRESS)
    // Neither secret typed at a hidden prompt was echoed.
    expect(text).not.toContain(FIXTURE_PHRASE)
    expect(text.split(typedBack.type)).toHaveLength(2)

    // And the vault the binary wrote opens here with the same root and the same key.
    const vault = await unlockWithPassphrase(restored, readFileSync(restored, "utf8"), typedBack.type)
    try {
      expect(vault.index.entries.map((entry) => entry.address)).toEqual([FIXTURE_ADDRESS])
      expect(vault.index.hd.discovery).toMatchObject({ complete: false })
      const root = await decryptRoot(vault)
      expect([...root]).toEqual([...FIXTURE_ENTROPY])
      wipe(root)
    } finally {
      closeVault(vault)
    }
  })

  test("a 0.9.x reader still refuses the fixture, so the ED-8 guarantee holds on the real file", async () => {
    const { readKeystore } = await import("../wallet-keystore")
    await expect(readKeystore(readFileSync(fixturePath, "utf8"), FIXTURE_PASSPHRASE)).rejects.toThrow(
      "Unsupported keystore version 2",
    )
  })
})

describe("T49: the mirror's own build sees the same declarations", () => {
  test("the fixture and its builder are inside this package, so the mirror copies them", () => {
    // The mirror sees only `packages/cli`. A fixture living anywhere else in the monorepo would
    // pass here and be missing there, which is E21's failure class in a different costume.
    expect(fixturePath.startsWith(pkgDir)).toBe(true)
    expect(existsSync(join(pkgDir, "scripts", "build-vault-fixture.ts"))).toBe(true)
    expect(existsSync(join(pkgDir, "test-fixtures", "vault", "README.md"))).toBe(true)
  })

  test("the `files` list does not need to carry the fixture, because npm ships only dist", () => {
    const pkg = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8")) as { files: string[] }
    expect(pkg.files).toEqual(["dist", "README.md", "LICENSE"])
  })
})
