import { describe, expect, test } from "bun:test"
import {
  HYPERLIQUID_EXCHANGE_URLS,
  hyperliquidActionHash,
  hyperliquidApproveBuilderFeeTypedData,
  hyperliquidExchangeBody,
  hyperliquidL1TypedData,
  hyperliquidRelayBody,
  hyperliquidSplitSignature,
  msgpackEncode,
  type PerpsBuildToVerify,
  verifyPerpsBuild,
} from "./hyperliquid"
import fixture from "./hyperliquid.vectors.fixture.json"

// Vectors generated by the official Python SDK (scripts/hyperliquid-vectors.py in the Candle repo).
interface L1Vector {
  name: string
  kind: string
  action: Record<string, unknown>
  nonce: number
  msgpackHex: string
  actionHash: string
}
const l1 = (fixture.cases as unknown as L1Vector[]).filter((c) => c.kind === "l1")
const hex = (bytes: Uint8Array) => Buffer.from(bytes).toString("hex")

describe("encoding matches the official Python SDK", () => {
  test("there are vectors for every action type Candle builds", () => {
    const types = new Set(l1.map((c) => c.action.type))
    for (const type of ["order", "cancel", "modify", "updateLeverage", "updateIsolatedMargin"]) {
      expect(types.has(type)).toBe(true)
    }
  })
  for (const vector of l1) {
    test(`${vector.name}: msgpack and action hash`, () => {
      expect(hex(msgpackEncode(vector.action))).toBe(vector.msgpackHex)
      expect(hyperliquidActionHash(vector.action, vector.nonce)).toBe(vector.actionHash)
    })
  }
})

const BUILDER = "0x7a2b3c4d5e6f708192a3b4c5d6e7f80910a1b2c3"
const OTHER = "0x1111111111111111111111111111111111111111"

function orderBuild(overrides: Partial<PerpsBuildToVerify> = {}, action?: Record<string, unknown>): PerpsBuildToVerify {
  const a = action ?? {
    type: "order",
    orders: [
      { a: 0, b: true, p: "60000", s: "0.01", r: false, t: { limit: { tif: "Gtc" } }, c: `0x${"1".repeat(32)}` },
    ],
    grouping: "na",
    builder: { b: BUILDER, f: 100 },
  }
  const nonce = overrides.nonce ?? 1_790_000_000_000
  return {
    network: "mainnet",
    nonce,
    action: a,
    typedData: hyperliquidL1TypedData(hyperliquidActionHash(a, nonce), "mainnet"),
    ...overrides,
  }
}

describe("verifyPerpsBuild refuses before any relay call", () => {
  test("an honest order passes", () => {
    expect(verifyPerpsBuild(orderBuild(), { builder: BUILDER })).toEqual({ ok: true, kind: "l1" })
  })

  test("an order with no builder (a Max order) passes", () => {
    const action = { type: "order", orders: [], grouping: "na" }
    expect(verifyPerpsBuild(orderBuild({}, action), { builder: BUILDER }).ok).toBe(true)
  })

  test("an action type Candle does not build: vaultTransfer, withdraw3, usdSend, approveAgent, subAccountTransfer", () => {
    for (const type of [
      "vaultTransfer",
      "withdraw3",
      "usdSend",
      "approveAgent",
      "subAccountTransfer",
      "createSubAccount",
    ]) {
      const result = verifyPerpsBuild(orderBuild({}, { type, vaultAddress: OTHER, isDeposit: true, usd: 1 }), {
        builder: BUILDER,
      })
      expect(result.ok).toBe(false)
    }
  })

  test("a builder that is not Candle's, or a fee over 0.1%", () => {
    const wrong = { type: "order", orders: [], grouping: "na", builder: { b: OTHER, f: 100 } }
    expect(verifyPerpsBuild(orderBuild({}, wrong), { builder: BUILDER }).ok).toBe(false)
    const greedy = { type: "order", orders: [], grouping: "na", builder: { b: BUILDER, f: 101 } }
    expect(verifyPerpsBuild(orderBuild({}, greedy), { builder: BUILDER }).ok).toBe(false)
    const cancelWithBuilder = { type: "cancel", cancels: [{ a: 0, o: 1 }], builder: { b: BUILDER, f: 1 } }
    expect(verifyPerpsBuild(orderBuild({}, cancelWithBuilder), { builder: BUILDER }).ok).toBe(false)
  })

  test("typed data that does not commit to the plaintext action or nonce", () => {
    const honest = orderBuild()
    const swapped = { ...honest, action: { ...honest.action, grouping: "normalTpsl" } }
    expect(verifyPerpsBuild(swapped, { builder: BUILDER }).ok).toBe(false)
    expect(verifyPerpsBuild({ ...honest, nonce: honest.nonce + 1 }, { builder: BUILDER }).ok).toBe(false)
  })

  test("the wrong network or source, a different domain, an extra key", () => {
    const honest = orderBuild()
    expect(verifyPerpsBuild(honest, { builder: BUILDER, network: "testnet" }).ok).toBe(false)
    const testnetTyped = {
      ...honest,
      network: undefined,
      typedData: hyperliquidL1TypedData(String(honest.typedData.message.connectionId), "testnet"),
    }
    expect(verifyPerpsBuild(testnetTyped, { builder: BUILDER }).ok).toBe(false)
    const otherChain = {
      ...honest,
      typedData: { ...honest.typedData, domain: { ...honest.typedData.domain, chainId: 1 } },
    }
    expect(verifyPerpsBuild(otherChain, { builder: BUILDER }).ok).toBe(false)
    const extra = { ...honest, typedData: { ...honest.typedData, message: { ...honest.typedData.message, extra: 1 } } }
    expect(verifyPerpsBuild(extra, { builder: BUILDER }).ok).toBe(false)
    const otherType = { ...honest, typedData: { ...honest.typedData, primary_type: "HyperliquidTransaction:Withdraw" } }
    expect(verifyPerpsBuild(otherType, { builder: BUILDER }).ok).toBe(false)
  })

  test("a build for a different wallet", () => {
    expect(verifyPerpsBuild(orderBuild({ address: OTHER }), { builder: BUILDER, address: BUILDER }).ok).toBe(false)
  })

  test("no builder to check against is a refusal, not a pass", () => {
    expect(verifyPerpsBuild(orderBuild(), { builder: "" }).ok).toBe(false)
  })
})

describe("setup's builder approval", () => {
  const nonce = 1_790_000_000_001
  const honest: PerpsBuildToVerify = {
    network: "mainnet",
    nonce,
    typedData: hyperliquidApproveBuilderFeeTypedData(BUILDER, nonce),
    action: {
      type: "approveBuilderFee",
      hyperliquidChain: "Mainnet",
      signatureChainId: "0xa4b1",
      maxFeeRate: "0.1%",
      builder: BUILDER,
      nonce,
    },
  }
  test("Candle's builder at 0.1% on Mainnet passes", () => {
    expect(verifyPerpsBuild(honest, { builder: BUILDER })).toEqual({ ok: true, kind: "approveBuilderFee" })
  })
  test("another builder, another rate, Testnet, or an action that differs from its typed data", () => {
    expect(
      verifyPerpsBuild(
        { ...honest, typedData: hyperliquidApproveBuilderFeeTypedData(OTHER, nonce) },
        { builder: BUILDER },
      ).ok,
    ).toBe(false)
    const rate = { ...honest.typedData, message: { ...honest.typedData.message, maxFeeRate: "1%" } }
    expect(verifyPerpsBuild({ ...honest, typedData: rate }, { builder: BUILDER }).ok).toBe(false)
    const testnet = { ...honest.typedData, message: { ...honest.typedData.message, hyperliquidChain: "Testnet" } }
    expect(verifyPerpsBuild({ ...honest, typedData: testnet }, { builder: BUILDER }).ok).toBe(false)
    expect(verifyPerpsBuild({ ...honest, action: { ...honest.action, builder: OTHER } }, { builder: BUILDER }).ok).toBe(
      false,
    )
  })
})

describe("submission", () => {
  test("splits a 65-byte signature, normalizing v", () => {
    const sig = `0x${"a".repeat(64)}${"b".repeat(64)}01`
    expect(hyperliquidSplitSignature(sig)).toEqual({ r: `0x${"a".repeat(64)}`, s: `0x${"b".repeat(64)}`, v: 28 })
    expect(() => hyperliquidSplitSignature("0x1234")).toThrow()
  })
  test("the exchange body and relay body", () => {
    const sig = `0x${"a".repeat(64)}${"b".repeat(64)}1b`
    expect(hyperliquidExchangeBody({ type: "cancel" }, 5, sig)).toEqual({
      action: { type: "cancel" },
      nonce: 5,
      signature: { r: `0x${"a".repeat(64)}`, s: `0x${"b".repeat(64)}`, v: 27 },
      vaultAddress: null,
      expiresAfter: null,
    })
    const typed = hyperliquidL1TypedData(`0x${"0".repeat(64)}`, "mainnet")
    expect(hyperliquidRelayBody(typed)).toEqual({ method: "eth_signTypedData_v4", params: { typed_data: typed } })
    expect(HYPERLIQUID_EXCHANGE_URLS.mainnet).toBe("https://api.hyperliquid.xyz/exchange")
  })
})
