/**
 * Hyperliquid perps (Candle spec 2026-10-01-hyperliquid-perps-tee-design.md, HL-ED-2, HL-ED-5): the
 * client half of "Candle builds each action, the client submits it".
 *
 * A perps build route returns a plaintext Hyperliquid action, the nonce, and the EIP-712 typed data
 * Candle stamped a relay claim over. Before anything is signed, the client recomputes the action
 * hash from the plaintext and checks it is the hash inside the typed data, that the action type is
 * one of the five Candle builds, that the builder is Candle's (or absent on a Max order), and that
 * the typed data is exactly one of the two shapes the relay forwards. Only then does it ask the
 * relay to sign, and it submits the signed action to Hyperliquid itself. A mismatch is a client
 * refusal, with no relay call. This is what stops a dishonest build: the TEE wallet signs only a
 * hash, so nothing downstream can read the action back.
 *
 * The encoding is the official Python SDK's `action_hash` (msgpack of the action, the nonce as
 * 8 big-endian bytes, a zero byte for "no vault", keccak-256), byte for byte:
 * `hyperliquid.vectors.fixture.json` holds vectors generated by that SDK, and `hyperliquid.test.ts`
 * reproduces every one.
 *
 * `packages/cli/src/hyperliquid.ts` and `packages/mcp/src/hyperliquid.ts` are byte-identical copies
 * of this file (drift tests enforce it), and the Candle API carries the same encoder. Self-contained
 * on purpose: its only import is keccak.
 */
import { keccak_256 } from "@noble/hashes/sha3"

export type HyperliquidNetwork = "mainnet" | "testnet"

/** The L1 action types a Candle build may carry. Anything else is refused before signing. */
export const HYPERLIQUID_ALLOWED_ACTION_TYPES = [
  "order",
  "cancel",
  "modify",
  "updateLeverage",
  "updateIsolatedMargin",
] as const

/** Hyperliquid's `/exchange` endpoint per network. The client never takes this from the server. */
export const HYPERLIQUID_EXCHANGE_URLS: Readonly<Record<HyperliquidNetwork, string>> = {
  mainnet: "https://api.hyperliquid.xyz/exchange",
  testnet: "https://api.hyperliquid-testnet.xyz/exchange",
}

/** Hyperliquid's public `/info` endpoint per network. */
export const HYPERLIQUID_INFO_URLS: Readonly<Record<HyperliquidNetwork, string>> = {
  mainnet: "https://api.hyperliquid.xyz/info",
  testnet: "https://api.hyperliquid-testnet.xyz/info",
}

/**
 * Candle's builder address as this release knows it, for `verifyPerpsBuild`. Null until the address
 * is fixed for a published release; until then a client pins it from its own configuration.
 */
export const CANDLE_HYPERLIQUID_BUILDER_ADDRESS: string | null = null

/** The builder fee Candle charges at most, in tenths of a basis point (0.1%), and as setup signs it. */
export const HYPERLIQUID_MAX_BUILDER_FEE_TENTHS_BPS = 100
export const HYPERLIQUID_MAX_BUILDER_FEE_RATE = "0.1%"

/** `signatureChainId` for the ApproveBuilderFee domain (chain id 42161). */
export const HYPERLIQUID_SIGNATURE_CHAIN_ID = "0xa4b1"

const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"

// ── msgpack, exactly as Python's msgpack.packb encodes the types an action uses ──────────────

const UINT64_MAX = (1n << 64n) - 1n
const INT64_MIN = -(1n << 63n)

function pushUint(out: number[], value: bigint, width: number): void {
  for (let i = width - 1; i >= 0; i--) out.push(Number((value >> BigInt(i * 8)) & 0xffn))
}

function packInteger(out: number[], value: bigint): void {
  if (value >= 0n) {
    if (value > UINT64_MAX) throw new Error("msgpack: integer above uint64")
    if (value < 0x80n) out.push(Number(value))
    else if (value <= 0xffn) {
      out.push(0xcc)
      pushUint(out, value, 1)
    } else if (value <= 0xffffn) {
      out.push(0xcd)
      pushUint(out, value, 2)
    } else if (value <= 0xffffffffn) {
      out.push(0xce)
      pushUint(out, value, 4)
    } else {
      out.push(0xcf)
      pushUint(out, value, 8)
    }
    return
  }
  if (value < INT64_MIN) throw new Error("msgpack: integer below int64")
  if (value >= -32n) out.push(Number(value & 0xffn))
  else if (value >= -128n) {
    out.push(0xd0)
    pushUint(out, value & 0xffn, 1)
  } else if (value >= -32768n) {
    out.push(0xd1)
    pushUint(out, value & 0xffffn, 2)
  } else if (value >= -2147483648n) {
    out.push(0xd2)
    pushUint(out, value & 0xffffffffn, 4)
  } else {
    out.push(0xd3)
    pushUint(out, value & UINT64_MAX, 8)
  }
}

function packHeader(out: number[], length: number, fixBase: number, fixMax: number, codes: number[]): void {
  if (length <= fixMax) {
    out.push(fixBase | length)
    return
  }
  const [c8, c16, c32] = codes
  if (c8 !== undefined && c8 !== 0 && length <= 0xff) {
    out.push(c8)
    pushUint(out, BigInt(length), 1)
  } else if (length <= 0xffff) {
    out.push(c16 as number)
    pushUint(out, BigInt(length), 2)
  } else {
    out.push(c32 as number)
    pushUint(out, BigInt(length), 4)
  }
}

function packValue(out: number[], value: unknown): void {
  if (value === null) out.push(0xc0)
  else if (value === false) out.push(0xc2)
  else if (value === true) out.push(0xc3)
  else if (typeof value === "bigint") packInteger(out, value)
  else if (typeof value === "number") {
    // An action never carries a float: prices and sizes are decimal strings.
    if (!Number.isSafeInteger(value)) throw new Error(`msgpack: ${value} is not a safe integer`)
    packInteger(out, BigInt(value))
  } else if (typeof value === "string") {
    const bytes = new TextEncoder().encode(value)
    packHeader(out, bytes.length, 0xa0, 31, [0xd9, 0xda, 0xdb])
    for (const b of bytes) out.push(b)
  } else if (Array.isArray(value)) {
    packHeader(out, value.length, 0x90, 15, [0, 0xdc, 0xdd])
    for (const item of value) packValue(out, item)
  } else if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(([, v]) => v !== undefined)
    for (const [key] of entries) {
      // JavaScript enumerates integer-like keys first; no action key is one.
      if (/^(0|[1-9][0-9]*)$/.test(key)) throw new Error(`msgpack: integer-like key "${key}"`)
    }
    packHeader(out, entries.length, 0x80, 15, [0, 0xde, 0xdf])
    for (const [key, item] of entries) {
      packValue(out, key)
      packValue(out, item)
    }
  } else {
    throw new Error(`msgpack: cannot encode a ${typeof value}`)
  }
}

/** Python `msgpack.packb(value)` for the JSON-like values an action uses. Throws on anything else. */
export function msgpackEncode(value: unknown): Uint8Array {
  const out: number[] = []
  packValue(out, value)
  return Uint8Array.from(out)
}

function toHex(bytes: Uint8Array): string {
  let out = ""
  for (const b of bytes) out += b.toString(16).padStart(2, "0")
  return out
}

/** The official SDK's `action_hash(action, None, nonce, None)`, as `0x` + 64 hex. */
export function hyperliquidActionHash(action: unknown, nonce: number | bigint): string {
  const n = BigInt(nonce)
  if (n < 0n || n > UINT64_MAX) throw new Error("hyperliquidActionHash: nonce out of range")
  const out = Array.from(msgpackEncode(action))
  pushUint(out, n, 8)
  out.push(0)
  return `0x${toHex(keccak_256(Uint8Array.from(out)))}`
}

// ── The two typed-data shapes the relay forwards ─────────────────────────────────────────

export interface HyperliquidTypedData {
  domain: Record<string, unknown>
  types: Record<string, { name: string; type: string }[]>
  primary_type: string
  message: Record<string, unknown>
}

export function hyperliquidL1TypedData(connectionId: string, network: HyperliquidNetwork): HyperliquidTypedData {
  return {
    domain: { name: "Exchange", version: "1", chainId: 1337, verifyingContract: ZERO_ADDRESS },
    types: {
      Agent: [
        { name: "source", type: "string" },
        { name: "connectionId", type: "bytes32" },
      ],
    },
    primary_type: "Agent",
    message: { source: network === "mainnet" ? "a" : "b", connectionId },
  }
}

export function hyperliquidApproveBuilderFeeTypedData(builder: string, nonce: number): HyperliquidTypedData {
  return {
    domain: { name: "HyperliquidSignTransaction", version: "1", chainId: 42161, verifyingContract: ZERO_ADDRESS },
    types: {
      "HyperliquidTransaction:ApproveBuilderFee": [
        { name: "hyperliquidChain", type: "string" },
        { name: "maxFeeRate", type: "string" },
        { name: "builder", type: "address" },
        { name: "nonce", type: "uint64" },
      ],
    },
    primary_type: "HyperliquidTransaction:ApproveBuilderFee",
    message: {
      hyperliquidChain: "Mainnet",
      maxFeeRate: HYPERLIQUID_MAX_BUILDER_FEE_RATE,
      builder: builder.toLowerCase(),
      nonce,
    },
  }
}

/**
 * Deterministic JSON with object keys sorted by UTF-16 code unit at every level: RFC 8785 for the
 * values a typed-data relay body holds (strings, safe integers, booleans, arrays, objects). Used to
 * compare two values structurally, and as the payload a Privy authorization signature covers.
 */
export function hyperliquidCanonicalJson(value: unknown): string {
  return canonical(value)
}

function canonical(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value)
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`
  const record = value as Record<string, unknown>
  return `{${Object.keys(record)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`)
    .join(",")}}`
}

function sameValue(a: unknown, b: unknown): boolean {
  return canonical(a) === canonical(b)
}

// ── Verify before sign (HL-ED-5) ─────────────────────────────────────────────────────────

/** The part of a Candle perps build response the check reads. */
export interface PerpsBuildToVerify {
  network?: string
  nonce: number
  action: Record<string, unknown>
  typedData: HyperliquidTypedData
  address?: string
}

export interface VerifyPerpsBuildOptions {
  /** The network this client trades on. Default mainnet. */
  network?: HyperliquidNetwork
  /**
   * Candle's builder address, as this client knows it independently of the build. Orders must
   * name exactly this builder (or none), and setup must approve exactly it.
   */
  builder: string
  /** The wallet address this client expects to act for, when it knows it. */
  address?: string
  closeOrder?: { asset: number; isBuy: boolean; size: string }
  /** Bind the plaintext action to the method and arguments the caller actually requested. */
  intent?: {
    method: "setup" | "open" | "close" | "cancel" | "modify" | "leverage" | "margin"
    params: Record<string, unknown>
  }
}

export type PerpsBuildCheck = { ok: true; kind: "l1" | "approveBuilderFee" } | { ok: false; reason: string }

const EVM_ADDRESS_RE = /^0x[0-9a-fA-F]{40}$/

function checkBuilderField(action: Record<string, unknown>, builder: string): string | null {
  if (!("builder" in action) || action.builder === undefined) return null
  const field = action.builder as { b?: unknown; f?: unknown }
  if (typeof field !== "object" || field === null) return "builder field is not an object"
  if (typeof field.b !== "string" || field.b.toLowerCase() !== builder.toLowerCase()) {
    return "the order names a builder that is not Candle's"
  }
  if (
    typeof field.f !== "number" ||
    !Number.isInteger(field.f) ||
    field.f <= 0 ||
    field.f > HYPERLIQUID_MAX_BUILDER_FEE_TENTHS_BPS
  ) {
    return "the builder fee is outside Candle's 0.1% maximum"
  }
  return null
}

function decimal(value: unknown): bigint | null {
  if (typeof value !== "string" || !/^-?(0|[1-9][0-9]*)(\.[0-9]{1,18})?$/.test(value)) return null
  const negative = value.startsWith("-")
  const [whole = "0", frac = ""] = (negative ? value.slice(1) : value).split(".")
  const n = BigInt(whole) * 10n ** 18n + BigInt(frac.padEnd(18, "0"))
  return negative ? -n : n
}

function checkActionIntent(action: Record<string, unknown>, intent: VerifyPerpsBuildOptions["intent"]): string | null {
  const mainAsset = (a: unknown) => typeof a === "number" && Number.isInteger(a) && a >= 0 && a < 10000
  const orderList = action.type === "order" ? action.orders : action.type === "modify" ? [action.order] : []
  if (!Array.isArray(orderList)) return "invalid orders"
  for (const raw of orderList) {
    if (!raw || typeof raw !== "object") return "invalid order"
    const o = raw as Record<string, unknown>
    if (!mainAsset(o.a)) return "order asset is outside the main perp universe"
    if (
      typeof o.b !== "boolean" ||
      typeof o.r !== "boolean" ||
      (decimal(o.s) ?? 0n) <= 0n ||
      (decimal(o.p) ?? 0n) <= 0n
    )
      return "invalid order side, size, price or reduce-only flag"
  }
  if (action.type === "cancel") {
    if (!Array.isArray(action.cancels) || action.cancels.length !== 1 || !mainAsset(action.cancels[0]?.a))
      return "invalid cancel asset"
  }
  if ((action.type === "updateLeverage" || action.type === "updateIsolatedMargin") && !mainAsset(action.asset))
    return "invalid action asset"
  if (!intent) return null
  const { method, params: p } = intent
  const types = {
    setup: "approveBuilderFee",
    open: "order",
    close: "order",
    cancel: "cancel",
    modify: "modify",
    leverage: "updateLeverage",
    margin: "updateIsolatedMargin",
  }
  if (action.type !== types[method]) return "action type does not match the requested method"
  if (method === "leverage") {
    if (action.leverage !== p.leverage || action.isCross !== (p.mode !== "isolated"))
      return "leverage or mode does not match the request"
  }
  if (method === "margin") {
    const amount = decimal(p.amount)
    if (
      amount === null ||
      amount % 10n ** 12n !== 0n ||
      !Number.isSafeInteger(action.ntli) ||
      BigInt(action.ntli as number) !== amount / 10n ** 12n ||
      action.isBuy !== true
    )
      return "isolated margin amount does not match the request"
  }
  if (method === "open" || method === "close" || method === "modify") {
    const list = orderList as Record<string, unknown>[]
    const first = list[0]
    if (!first) return "missing requested order"
    const typ = first.t as { limit?: { tif?: unknown } } | undefined
    if (!typ?.limit) return "requested order is not a limit/IOC order"
    if (method === "open") {
      const buy = p.side === "long" || p.side === "buy"
      if (first.b !== buy || first.r !== false || decimal(first.s) !== decimal(p.size))
        return "order side, size or reduce-only flag does not match the request"
      const tif = (p.type ?? (p.price === undefined ? "market" : "limit")) === "market" ? "Ioc" : (p.tif ?? "Gtc")
      if (typ.limit.tif !== tif) return "order time in force does not match the request"
      const triggers = [
        ["takeProfit", "tp"],
        ["stopLoss", "sl"],
      ].filter(([field]) => p[field as string] != null)
      if (list.length !== 1 + triggers.length || action.grouping !== (triggers.length ? "normalTpsl" : "na"))
        return "unexpected extra orders or grouping"
      for (let i = 0; i < triggers.length; i++) {
        const [field, kind] = triggers[i] as [string, string]
        const leg = list[i + 1]
        if (!leg) return "missing trigger order"
        const trigger = (leg.t as { trigger?: { tpsl?: unknown; triggerPx?: unknown; isMarket?: unknown } })?.trigger
        if (
          leg.a !== first.a ||
          leg.b !== !buy ||
          leg.r !== true ||
          decimal(leg.s) !== decimal(p.size) ||
          trigger?.tpsl !== kind ||
          trigger.isMarket !== true ||
          decimal(trigger.triggerPx) !== decimal(p[field])
        )
          return "trigger side, size, reduce-only flag or price does not match the request"
      }
    } else {
      if (list.length !== 1) return "unexpected extra orders"
      if (
        method === "close" &&
        (first.r !== true ||
          typ.limit.tif !== "Ioc" ||
          (p.size != null && (decimal(first.s) ?? 0n) > (decimal(p.size) ?? 0n)))
      )
        return "close size or reduce-only flag does not match the request"
      if (method === "modify" && p.size != null && decimal(first.s) !== decimal(p.size))
        return "replacement size does not match the request"
    }
    if (p.price != null && decimal(first.p) !== decimal(p.price)) return "order price does not match the request"
  }
  return null
}

/** Read the position directly from the pinned venue before signing a close. The request
 * names no side and can omit size, so neither may be inferred from the build's preview.
 */
export async function hyperliquidCloseOrder(
  fetcher: (url: string, init?: RequestInit) => Promise<{ ok: boolean; text(): Promise<string> }>,
  network: HyperliquidNetwork,
  address: string,
  params: Record<string, unknown>,
): Promise<{ asset: number; isBuy: boolean; size: string }> {
  const read = async (body: Record<string, unknown>) => {
    const res = await fetcher(HYPERLIQUID_EXCHANGE_URLS[network].replace("/exchange", "/info"), {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(body),
    })
    if (!res.ok) throw new Error("Cannot read the close position from Hyperliquid")
    return JSON.parse(await res.text())
  }
  const [meta, state] = await Promise.all([read({ type: "meta" }), read({ type: "clearinghouseState", user: address })])
  const coin = String(params.coin).toUpperCase()
  const asset = (meta.universe as { name: string }[]).findIndex((m) => m.name.toUpperCase() === coin)
  const szi = (state.assetPositions as { position: { coin: string; szi: string } }[]).find(
    (p) => p.position.coin.toUpperCase() === coin,
  )?.position.szi
  const signed = decimal(szi)
  if (asset < 0 || asset >= 10000 || signed === null || signed === 0n)
    throw new Error("No main-universe position to close")
  const held = signed < 0n ? -signed : signed
  const asked = params.size == null ? held : decimal(params.size)
  if (asked === null || asked <= 0n) throw new Error("Invalid close size")
  const size = asked < held ? String(params.size) : String(szi).replace(/^-/, "")
  return { asset, isBuy: signed < 0n, size }
}

/**
 * Check a build before signing it. Never throws; a refusal names what failed. Callers must not
 * sign, and must not call the relay, unless this returns `ok: true`.
 */
export function verifyPerpsBuild(build: PerpsBuildToVerify, opts: VerifyPerpsBuildOptions): PerpsBuildCheck {
  try {
    const network = opts.network ?? "mainnet"
    if (!EVM_ADDRESS_RE.test(opts.builder))
      return { ok: false, reason: "no valid Candle builder address to check against" }
    if (build.network !== undefined && build.network !== network) {
      return { ok: false, reason: `the build is for ${build.network}, this client trades ${network}` }
    }
    if (opts.address && build.address && build.address.toLowerCase() !== opts.address.toLowerCase()) {
      return { ok: false, reason: "the build is for a different wallet" }
    }
    if (!Number.isSafeInteger(build.nonce) || build.nonce <= 0) return { ok: false, reason: "invalid nonce" }
    const typed = build.typedData
    if (!typed || typeof typed !== "object") return { ok: false, reason: "no typed data" }
    const action = build.action
    if (!action || typeof action !== "object") return { ok: false, reason: "no action" }

    const intentRefusal = checkActionIntent(action, opts.intent)
    if (intentRefusal) return { ok: false, reason: intentRefusal }
    if (opts.closeOrder) {
      const order = (action.orders as Record<string, unknown>[])[0]
      if (
        !order ||
        order.a !== opts.closeOrder.asset ||
        order.b !== opts.closeOrder.isBuy ||
        decimal(order.s) !== decimal(opts.closeOrder.size) ||
        order.r !== true
      )
        return { ok: false, reason: "close side, asset or size does not match the requested position" }
    }

    if (typed.primary_type === "Agent") {
      const type = action.type
      if (typeof type !== "string" || !(HYPERLIQUID_ALLOWED_ACTION_TYPES as readonly string[]).includes(type)) {
        return { ok: false, reason: `action type ${String(type)} is not one Candle builds` }
      }
      if (type === "order") {
        const refusal = checkBuilderField(action, opts.builder)
        if (refusal) return { ok: false, reason: refusal }
      } else if ("builder" in action) {
        return { ok: false, reason: `a ${type} action carries no builder` }
      }
      if ("vaultAddress" in action) return { ok: false, reason: "the action names a vault" }
      const expected = hyperliquidL1TypedData(hyperliquidActionHash(action, build.nonce), network)
      if (!sameValue(typed, expected)) {
        return { ok: false, reason: "the typed data does not commit to this action and nonce" }
      }
      return { ok: true, kind: "l1" }
    }

    if (typed.primary_type === "HyperliquidTransaction:ApproveBuilderFee") {
      const expected = hyperliquidApproveBuilderFeeTypedData(opts.builder, build.nonce)
      if (!sameValue(typed, expected)) {
        return { ok: false, reason: "the builder approval is not Candle's builder at 0.1% on Mainnet" }
      }
      const expectedAction = {
        type: "approveBuilderFee",
        hyperliquidChain: "Mainnet",
        signatureChainId: HYPERLIQUID_SIGNATURE_CHAIN_ID,
        maxFeeRate: HYPERLIQUID_MAX_BUILDER_FEE_RATE,
        builder: opts.builder.toLowerCase(),
        nonce: build.nonce,
      }
      if (!sameValue(action, expectedAction)) {
        return { ok: false, reason: "the approval action does not match its typed data" }
      }
      return { ok: true, kind: "approveBuilderFee" }
    }
    return { ok: false, reason: `primary type ${String(typed.primary_type)} is not one the relay signs` }
  } catch (err) {
    return { ok: false, reason: err instanceof Error ? err.message : "unreadable build" }
  }
}

// ── Submission ────────────────────────────────────────────────────────────────────────────

/** A 65-byte `0x` signature split the way `/exchange` takes it. */
export function hyperliquidSplitSignature(signature: string): { r: string; s: string; v: number } {
  if (!/^0x[0-9a-fA-F]{130}$/.test(signature)) throw new Error("Not a 65-byte signature")
  let v = Number.parseInt(signature.slice(130, 132), 16)
  if (v < 27) v += 27
  return { r: `0x${signature.slice(2, 66)}`, s: `0x${signature.slice(66, 130)}`, v }
}

/** The `/exchange` request body for a signed action. */
export function hyperliquidExchangeBody(action: Record<string, unknown>, nonce: number, signature: string) {
  return { action, nonce, signature: hyperliquidSplitSignature(signature), vaultAddress: null, expiresAfter: null }
}

/** The relay body (Privy's wallet-RPC wire shape) for typed data. */
export function hyperliquidRelayBody(typedData: HyperliquidTypedData) {
  return { method: "eth_signTypedData_v4" as const, params: { typed_data: typedData } }
}
