/**
 * Builds the committed vault fixture (Ember Phase 2, BE-136, CC-09).
 *
 * Run by hand when the FORMAT changes, never in CI:
 *
 *     bun scripts/build-vault-fixture.ts
 *
 * CC-09 asks every Phase 2 PR to open the same committed vault under `bun test` in the monorepo,
 * in the exported mirror before the release build, and by executing the compiled binary. A fixture
 * regenerated by the test that reads it would prove only that the code agrees with itself, which
 * is why this is a script and the file it writes is committed: the bytes a later PR opens are the
 * bytes this PR wrote, and a bundler or runtime difference that changed a derived address would
 * show up as a failure to open them.
 *
 * The fixture carries the DEFAULT ED-3 cost (64 MiB, t = 3), not the tests' floor, because it is
 * the one artifact that should look exactly like a real vault. Opening it therefore costs about a
 * second, which is why it is opened once per shape rather than once per assertion.
 *
 * Its passphrase, root entropy and phrase are in `src/vault/test-vault.ts` in the clear. They are
 * synthetic: the entropy is 0x00 01 02 ... 1f, which no generator would ever produce.
 */
import { mkdir, writeFile } from "node:fs/promises"
import { join, resolve } from "node:path"
import { createVault, freshHdRecord } from "../src/vault/create"
import { DERIVATION_SCHEME, deriveSolanaKey, solanaVaultPath } from "../src/vault/hd"
import { wipe } from "../src/vault/hygiene"
import { closeVault, commitVault, freshKeyId, sealKeyBlob } from "../src/vault/store"
import { FIXTURE_ENTROPY, FIXTURE_PASSPHRASE, testClock } from "../src/vault/test-vault"

const outDir = resolve(import.meta.dir, "..", "test-fixtures", "vault")
const outPath = join(outDir, "vault.enc")

await mkdir(outDir, { recursive: true })

const entropy = Uint8Array.from(FIXTURE_ENTROPY)
const vault = await createVault(
  {
    path: outPath,
    passphrase: FIXTURE_PASSPHRASE,
    strength: "generated-103",
    rootEntropy: entropy,
    hd: freshHdRecord(),
  },
  testClock,
)

// One derived key, so the fixture exercises the root blob, a key blob, and step 5's re-derivation.
const path = solanaVaultPath(0)
const derived = await deriveSolanaKey(entropy, path)
const keyId = freshKeyId()
const blob = await sealKeyBlob(vault, keyId, derived.secret64)

await commitVault(
  vault,
  {
    index: {
      hd: { ...vault.index.hd, nextIndex: { ...vault.index.hd.nextIndex, solanaVault: 1 } },
      entries: [
        {
          id: keyId,
          chain: "solana",
          curve: "ed25519",
          address: derived.address,
          label: "fixture key 0",
          createdAt: new Date(testClock.now()).toISOString(),
          role: "vault",
          origin: "derived",
          derivation: { scheme: DERIVATION_SCHEME, path },
          exposure: { everRemoteExposed: false, everExported: false },
        },
      ],
    },
    addKeys: [blob],
  },
  testClock,
)

wipe(derived.secret64, entropy)
closeVault(vault)

// The sidecar is NOT part of the fixture: ED-6 makes its absence a warning rather than a refusal,
// and a committed one would carry this machine's generation into every later test.
await writeFile(
  join(outDir, "README.md"),
  `# Vault fixture (Ember Phase 2, CC-09)

Generated by \`bun scripts/build-vault-fixture.ts\`. Do not edit by hand.

One \`candle-vault\` version 2 file: one passphrase envelope at ED-3's default cost, the root blob,
and one derived Solana key at \`${path}\` (\`${derived.address}\`).

The passphrase, the root entropy and the 24-word phrase are in \`src/vault/test-vault.ts\`, in the
clear and on purpose. They are synthetic -- the entropy is \`0x00 01 02 ... 1f\` -- and this file
holds nothing else.

\`vault-parity.test.ts\` opens it under \`bun test\` and by executing the compiled binary; the mirror
runs the same test before it builds a release.
`,
  "utf8",
)

process.stdout.write(`wrote ${outPath}\n  address ${derived.address}\n  path    ${path}\n`)
